version: "3"
services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 3000:3000
    command: yarn start
    volumes:
      - ./frontend:/frontend
      - node_modules:/frontend/node_modules
volumes:
  node_modules:
